### PR TITLE
feat: create proposal tx method

### PR DESCRIPTION
**Pull request by LukasDeco**

### CODE REVIEW

**Comment by metaproph3t** [comment]
what's the purpose of this change?

**Comment by LukasDeco** [comment]
> what's the purpose of this change?

Actually I need to make a change here. But the purpose is to just create a method for proposal initialization. I will need a proposal that will return an array of the transactions in the correct order and that we can sign them and send them to the jito bundle. That's what I'm working on here essentially but... this doesn't do that obviously because it uses .rpc(). This I guess will just work on devnet and won't really work on mainnet too well so... I might just mark this as draft for now.

**Comment by LukasDeco** [comment]
@metaproph3t this is ready now but not sure why anchor test is failing?

**Review by metaproph3t — APPROVED** [review]
LGTM

**Pull request merged**
