### PR TITLE
Add new languages to docs

### PR DESCRIPTION
**Pull request by 92GC**
Add new languages to docs

### CODE REVIEW

**Comment by 92GC** [comment]
- Following [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
- Dividing languages into separate spaces, following [this method](https://docs.gitbook.com/published-documentation/publish-multiple-spaces-on-one-site)

**Comment by metaproph3t** [comment]
Huh, when I click on "fr" or "es" I just see english

**Comment by 92GC** [comment]
# Background
- Crowdin wanted to charge $4600 for 10 languages. GPT 4o costs ~$3
image
- I have manually updated Mandarin so it is now perfect. GPT-4o was 98% accurate. 
- Mandarin is the 80/20 translation. But adding others can be done in a few minutes with the new scripts

# Translation steps that need to be done on .gitbook.com
- We need to use the gitbook website to make new spaces. See [example here](https://docs.gitbook.com/published-documentation/publish-multiple-spaces-on-one-site).
- I am happy to do this if you give me administrator permissions.
- The new spaces should be called: 中文, Español, Português Brasileiro, Русский, Tiếng Việt, Türkçe, Français, 日本語, Italiano, English (renaming the current one).
- We should click [localise UI](https://www.youtube.com/watch?v=h-Zp3SuQvPo&ab_channel=GitBook) to translate gitbook UI strings. 

# Git hub actions and pipeline
- Decide if we should run these scripts in pipeline or locally.
- I don't have access to pipeline scripts

# Auxiliary fixes 
- Fixed the rubric.md page as it is not showing in [prod](https://docs.metadao.fi/futarchy/rubric)

# Fix for open graph image not showing 
- Here is how you fix the open-graph image:
- Click on docs sites
- Click on settings 
- Click Manage Social preview
- and then upload this image https://github.com/metaDAOproject/futarchy/blob/develop/docs/.gitbook/assets/metadao-og-image.jpg

**Comment by 92GC** [comment]
Ready for review

**Pull request merged**
